### ISSUE TITLE
values for buienalarm seem 100x too high

### ISSUE THREAD

**Issue by Mrten** [aex351/home-assistant-neerslag-app#21]
had the neerslag card, upgraded to neerslag app but both seem to have the buienalarm values 100 time too high, see image from nov 20 (no 60mm storm)

![9770A1BF-2904-4DBC-8A16-5EAC28EE041E](https://user-images.githubusercontent.com/1662703/142738759-c3d02689-b81b-4b00-876f-bf49b6f54f6f.jpeg)

```
  - platform: command_line
    command: python3 -c "import requests; import json; import random; dataRequest = requests.get('https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=XXXXX&lon=XXX&region=nl&c='+str(random.randint(0,9999))).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":'+dataRequest+'}'; print(data);"
    name: Neerslag_Buienalarm_Regen_Data
    json_attributes:
      - data
    value_template: 'last_changed: {{states.sensor.neerslag_buienalarm_regen_data.last_changed | default(now())}}'
    scan_interval: 300
  - platform: command_line
    command: python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=XXX&lon=XXX&c='+str(random.randint(0,9999))).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}'; print(data);"
    name: Neerslag_Buienradar_Regen_Data
    json_attributes:
      - data
    value_template: 'last_changed: {{states.sensor.neerslag_buienradar_regen_data.last_changed | default(now())}}'
    scan_interval: 300
```

(location edited to protect the innocent)
